db:
  image: rethinkdb
  volumes:
    - "$PWD:/data"

dummy:
  build: .
  links:
    - db:db
  environment:
    - DBURL=db:28015
    - PLATFORMURL=https://your-mattermost-instance.example.com
    - THREADCOUNT=20
    - THREADOFFSET=0
    - RAMPSEC=60
    - TESTPLAN=UserPartyTestPlan
    - TESTCHANNEL=test-pool-party
    - MESSAGEBREAK=10

# Web interface indevelopment
# web:
#   build: web
#   ports:
#     - "80:80"
#     - "443:443"
#   links:
#     - app:app
#   volumes:
#     - ./volumes/web/cert:/cert:ro
#     - /etc/localtime:/etc/localtime:ro
#   environment:
#     - MATTERMOST_ENABLE_SSL=false
#     - PLATFORM_PORT_80_TCP_PORT=80
